AddEditSelectDelete/Models/AddEditSelectDelete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AddEditSelectDelete.Models
{
    public class AddEditSelectDelete
    {
        public List<string> examplelist;
    }
}

AddEditSelectDelete/Controllers/AddEditSelectDeleteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace AddEditSelectDelete.Controllers
{
    public class AddEditSelectDeleteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Cancel(string vtupd)
        {
            if (ViewData["id"] != null)
            {
                ViewData.Clear();
            }


            if (vtupd == "webindex")
                return View("WebIndex");
            else
                return View("Index");
        }
        [HttpPost]
        public ActionResult Index(FormCollection frmc)
        {


            if (Request.Form["deptID"] != null && Request.Form["nme"] != null && Request.Form["grnme"] != null && Request.Form["mddate"] != null)
            {
                string departmentID = Request.Form["deptID"].ToString();
                string name = Request.Form["nme"].ToString();
                string groupename = Request.Form["grnme"].ToString();
                string modifieddate = Request.Form["mddate"].ToString();
                System.Data.SqlClient.SqlConnection connection = new System.Data.SqlClient.SqlConnection("Data Source=(localdb)\\LocalInstance;Initial Catalog=AdventureWorks2012;Integrated Security=True");
                string cmdtext = "UPDATE [HumanResources].[Department] SET [Name] = '" + name + "',[GroupName] = '" + groupename + "',[ModifiedDate] = '" + modifieddate + "' WHERE [DepartmentID] = " + departmentID + "";
                System.Data.SqlClient.SqlCommand command = new System.Data.SqlClient.SqlCommand(cmdtext, connection);
                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
                ViewData.Clear();


            }




            if (Request.Form["DepartmentID"] != null && Request.Form["Name"] != null && Request.Form["GroupName"] != null && Request.Form["ModifiedDate"] != null && Request.Form["EditingFormTrue"] != null)
            {
                // we pressed on edit

                ViewData["id"] = Request.Form["DepartmentID"].ToString();
                ViewData["name"] = Request.Form["Name"].ToString();
                ViewData["groupName"] = Request.Form["GroupName"].ToString();
                ViewData["modifiedDate"] = Request.Form["ModifiedDate"].ToString();

                ViewData.Clear();
            }



            if (Request.Form["NAMETOADD"] != null && Request.Form["GROUPNAMETOADD"] != null && Request.Form["MODIFIEDDATETOADD"] != null)
            {
                string nametoadd = Request.Form["NAMETOADD"].ToString();
                string groupenametoadd = Request.Form["GROUPNAMETOADD"].ToString();
                string modifieddatetoadd = Request.Form["MODIFIEDDATETOADD"].ToString();
                System.Data.SqlClient.SqlConnection connectionnewadd = new System.Data.SqlClient.SqlConnection("Data Source=(localdb)\\LocalInstance;Initial Catalog=AdventureWorks2012;Integrated Security=True");
                string cmdtextaddnew = "INSERT INTO [HumanResources].[Department]([Name],[GroupName],[ModifiedDate])VALUES('" + nametoadd + "','" + groupenametoadd + "','" + modifieddatetoadd + "')";
                System.Data.SqlClient.SqlCommand command = new System.Data.SqlClient.SqlCommand(cmdtextaddnew, connectionnewadd);
                connectionnewadd.Open();
                command.ExecuteNonQuery();
                connectionnewadd.Close();
                ViewData.Clear();


            }


            if (Request.Form["viewtoretupd"] != null)
                return View("WebIndex");

            else
                return View("Index");
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Update(string id, string name, string groupName, string modifiedDate)
        {
            string urlreferrer = Request.UrlReferrer.ToString();
            if (ViewData["currentview"].ToString() == "webview")
                return View("WebIndex");
            else
                return View("Index");
        }
        public ActionResult Edit(string id, string name, string groupName, string modifiedDate, string viewtoreturn)
        {

            if (id != null && name != null && groupName != null && modifiedDate != null)
            {
                ViewData["id"] = id;
                ViewData["name"] = name;
                ViewData["groupName"] = groupName;
                ViewData["modifiedDate"] = modifiedDate;
            }



            if (viewtoreturn == "webindex")
                return View("WebIndex");
            else
                return View("Index");

        }

        [HttpPost]
        public ActionResult Edit(FormCollection frm, string viewtoreturn)
        {

            if (Request.Form["deptID"] != null && Request.Form["nme"] != null && Request.Form["grnme"] != null && Request.Form["mddate"] != null)
            {
                string departmentID = Request.Form["deptID"].ToString();
                string name = Request.Form["nme"].ToString();
                string groupename = Request.Form["grnme"].ToString();
                string modifieddate = Request.Form["mddate"].ToString();
                System.Data.SqlClient.SqlConnection connection = new System.Data.SqlClient.SqlConnection("Data Source=(localdb)\\LocalInstance;Initial Catalog=AdventureWorks2012;Integrated Security=True");
                string cmdtext = "UPDATE [HumanResources].[Department] SET [Name] = '" + name + "',[GroupName] = '" + groupename + "',[ModifiedDate] = '" + modifieddate + "' WHERE [DepartmentID] = " + departmentID + "";
                System.Data.SqlClient.SqlCommand command = new System.Data.SqlClient.SqlCommand(cmdtext, connection);
                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
                ViewData.Clear();


            }


            if (viewtoreturn == "webindex")
                return View("WebIndex");
            else
                return View("Index");

        }


        public ActionResult Add(string viewtoretur)
        {
            ViewData["AddRecord"] = "AddRecord";


            if (viewtoretur == "webindex")
                return View("WebIndex");
            else
                return View("Index");
        }
        public ActionResult AddNew()
        {
            ViewData["AddNewRecord"] = "AddNewRecord";


            return View("Index");
        }
        public ActionResult Delete(string idtodel, string viewtoreturn)
        {
            string depidtodelete = idtodel;
            System.Data.SqlClient.SqlConnection connectionnewadd = new System.Data.SqlClient.SqlConnection("Data Source=(localdb)\\LocalInstance;Initial Catalog=AdventureWorks2012;Integrated Security=True");
            string cmdtextaddnew = "DELETE FROM [HumanResources].[Department] WHERE DepartmentID = " + depidtodelete;
            System.Data.SqlClient.SqlCommand command = new System.Data.SqlClient.SqlCommand(cmdtextaddnew, connectionnewadd);
            connectionnewadd.Open();
            command.ExecuteNonQuery();
            connectionnewadd.Close();
            ViewData.Clear();
            ViewData["rowdeletednotify"] = "Yes";


            if (viewtoreturn == "webindex")
                return View("WebIndex");
            else
                return View("Index");
        }

        public ActionResult WebIndex()
        {
            return View();
        }
    }
}

AddEditSelectDelete/Views/AddEditSelectDelete/WebIndex.cshtml
@{
    Layout = "~/Views/Shared/_AddEditSelectDelete.cshtml";
}


<script type="text/javascript">
    var counter = 0;
    var windowsize;
    var webindex = '/AddEditSelectDelete/WebIndex';
    var index = '/AddEditSelectDelete/Index';


            $(document).ready(function () {
                if (counter == 0) {
                    windowsize = $(window).width();
                    if (windowsize < 440) {
                        window.location = index;
                    }
                
                }
                counter++;

            });

            $(window).resize(function () {

                windowsize = $(window).width();
                if (windowsize > 440) {
                    window.location = webindex;
                }
                else
                {
                    window.location = index;
                }
            });

</script>


  @{ 

      string connectionString = "Data Source=(localdb)\\LocalInstance;Initial Catalog=AdventureWorks2012;Integrated Security=True";
      string query = "SELECT TOP 1000 [DepartmentID],[Name],[GroupName],[ModifiedDate]FROM [AdventureWorks2012].[HumanResources].[Department]";
      System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(connectionString);
      System.Data.SqlClient.SqlCommand cmd = new System.Data.SqlClient.SqlCommand(query, conn);
      System.Data.DataTable dtHR = new System.Data.DataTable();
      conn.Open();
      System.Data.SqlClient.SqlDataAdapter da = new System.Data.SqlClient.SqlDataAdapter(cmd);
      da.Fill(dtHR);
      conn.Close();
      da.Dispose();
  }
<form action="/AddEditSelectDelete/Index" method="post" name="frmSubmit">
    <h2>@Html.ActionLink("About", "About", "AddEditSelectDelete", null, null)</h2>
    <h3>Human Resources</h3>

    <table class="table  striped">
        <thead>
            <tr>
                <th class="text-left info"> <h2 id="__table__">DepartmentID</h2></th>
                <th class="text-left"><h2 id="__form__">Name</h2></th>
                <th class="text-left"><h2 id="__buttons__">GroupName</h2></th>
                <th class="text-left"><h2 id="__image__">ModifiedDate</h2></th>
                <th class="text-left"><h2 id="__tile__">OPTIONS</h2></th>
            </tr>
        </thead>
        <tbody>

            @if (ViewData["AddRecord"] != null && ViewData["AddRecord"].ToString() == "AddRecord")
            {
                for (int i = 0; i < dtHR.Rows.Count; i++)
                {
                    <tr class="">
                        <td>@dtHR.Rows[i]["DepartmentID"].ToString()</td>
                        <td class="right">@dtHR.Rows[i]["Name"].ToString()</td>
                        <td class="right">@dtHR.Rows[i]["GroupName"].ToString()</td>
                        <td class="right">@dtHR.Rows[i]["ModifiedDate"].ToString()</td>
                        <td class="right">
                            @Html.ActionLink("Edit", "Edit", "AddEditSelectDelete", new { id = dtHR.Rows[i]["DepartmentID"].ToString(), name = dtHR.Rows[i]["Name"].ToString(), groupName = dtHR.Rows[i]["GroupName"].ToString(), modifiedDate = dtHR.Rows[i]["ModifiedDate"].ToString() }, null)

                        </td>
                    </tr>
                }
                <tr>
                    <td></td>
                    <td>@Html.TextBox("NAMETOADD")</td>
                    <td>@Html.TextBox("GROUPNAMETOADD")</td>
                    <td>
                        <div class="input-control text" data-role="datepicker" data-effect="none" data-format='yyyy-mm-dd'>
                            @Html.TextBox("MODIFIEDDATETOADD")
                        </div>
                    </td>
                    <td>
                        @Html.Hidden("viewtoretupd", "webindex")
                        <input id="Submit1" type="submit" runat="server" value="Add New" class="m-btn blue fg-white">
                        @Html.ActionLink("Cancel", "Cancel", "AddEditSelectDelete", null, null)
                    </td>
                </tr>
            }
            else
            {
                if (ViewData["id"] == null && ViewData["name"] == null && ViewData["groupName"] == null && ViewData["modifiedDate"] == null)
                {
                    for (int i = 0; i < dtHR.Rows.Count; i++)
                    {
                        <tr class="">
                            <td>@dtHR.Rows[i]["DepartmentID"].ToString()</td>
                            <td class="right">@dtHR.Rows[i]["Name"].ToString()</td>
                            <td class="right">@dtHR.Rows[i]["GroupName"].ToString()</td>
                            <td class="right">@dtHR.Rows[i]["ModifiedDate"].ToString()</td>
                            <td class="right">
                                @Html.ActionLink("Edit", "Edit", "AddEditSelectDelete", new { id = dtHR.Rows[i]["DepartmentID"].ToString(), name = dtHR.Rows[i]["Name"].ToString(), groupName = dtHR.Rows[i]["GroupName"].ToString(), modifiedDate = dtHR.Rows[i]["ModifiedDate"].ToString(), viewtoreturn = "webindex" }, null)
                                @*<input type="submit" name="submitButton" value="Delete" class="m-btn purple fg-white" />*@
                                @Html.ActionLink("Delete", "Delete", "AddEditSelectDelete", new { idtodel = dtHR.Rows[i]["DepartmentID"].ToString(), viewtoreturn = "webindex" }, null)
                            </td>
                        </tr>

                    }

                    <tr class="info">
                        <td></td>
                        <td class="right"></td>
                        <td class="right"></td>
                        <td class="right"></td>
                        <td class="right">
                            @Html.ActionLink("Add", "Add", "AddEditSelectDelete", new { viewtoretur = "webindex" }, null)
                        </td>
                    </tr>

                }
                else
                {
                    for (int j = 0; j < dtHR.Rows.Count; j++)
                    {
                        int idtoedit = Convert.ToInt32(ViewData["id"].ToString());

                        if (dtHR.Rows[j]["DepartmentID"].ToString() == ViewData["id"].ToString())
                        {

                            <tr>
                                <td>@dtHR.Rows[j]["DepartmentID"].ToString()@Html.Hidden("deptID", dtHR.Rows[j]["DepartmentID"].ToString())</td>
                                <td>@Html.TextBox("nme", dtHR.Rows[j]["Name"].ToString())</td>
                                <td>@Html.TextBox("grnme", dtHR.Rows[j]["GroupName"].ToString())</td>
                                <td>@Html.TextBox("mddate", dtHR.Rows[j]["ModifiedDate"].ToString())</td>
                                <td>
                                    @Html.Hidden("viewtoretupd", "webindex")
                                    <input id="Submit2" type="submit" value="UPDATE" class="m-btn blue fg-white">
                                    @Html.ActionLink("Cancel", "Cancel", "AddEditSelectDelete", new { vtupd = "webindex" }, null)
                                </td>
                            </tr>

                        }
                        else
                        {

                            <tr class="">
                                <td>@dtHR.Rows[j]["DepartmentID"].ToString()</td>
                                <td>@dtHR.Rows[j]["Name"].ToString()</td>
                                <td>@dtHR.Rows[j]["GroupName"].ToString()</td>
                                <td>@dtHR.Rows[j]["ModifiedDate"].ToString()</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", "AddEditSelectDelete", new { id = dtHR.Rows[j]["DepartmentID"].ToString(), name = dtHR.Rows[j]["Name"].ToString(), groupName = dtHR.Rows[j]["GroupName"].ToString(), modifiedDate = dtHR.Rows[j]["ModifiedDate"].ToString() }, null)
                                    @Html.ActionLink("Delete", "Delete", "AddEditSelectDelete", new { idtodel = dtHR.Rows[j]["DepartmentID"].ToString() }, null)
                                </td>
                            </tr>
                        }
                    }
                }
            }



        </tbody>
    </table>

    </form>

AddEditSelectDelete/Views/Shared/_AddEditSelectDelete.cshtml
<!DOCTYPE html>

<head id="Head1" runat="server">
    <meta name="viewport" content="width=device-width" />
    <title>Responsive ASP.NET App</title>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link href="../../css/metro-bootstrap.css" rel="stylesheet" />
    <link href="../../css/m-buttons.css" rel="stylesheet" />
    <script src="../../js/metro.min.js"></script>
    <style type="text/css">
        ol {
            list-style-type: none;
            counter-reset: item;
            margin: 0;
            padding: 0;
        }

            ol > li {
                display: table;
                counter-increment: item;
                margin-bottom: 0.6em;
            }

                ol > li > ol > li {
                    margin-left: -3.0em;
                }

                ol > li:before {
                    content: counters(item, ".") ". ";
                    display: table-cell;
                    padding-right: 0.6em;
                }

        li ol > li {
            margin: 0;
        }

            li ol > li:before {
                content: counters(item, ":") " ";
            }
    </style>
</head>
<body class="metro">
    @RenderBody()
</body>